In [36]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [37]:
df = pd.read_csv("../data/Titanic_dataset.csv", usecols=['Age', 'SibSp', 'Parch', 'Survived', 'Pclass'])
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [38]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [39]:
df = df.dropna()

In [40]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
dtype: int64

In [41]:
X = df.drop(columns=['Survived'])
y = df['Survived']

## Without feature construction and splitting

In [42]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv = 20))

np.float64(0.6933333333333332)

## Feature construction

In [43]:
X['Family'] = X['SibSp'] + X['Parch'] + 1

In [44]:
X.head()

   Pclass   Age  SibSp  Parch  Family
0       3  22.0      1      0       2
1       1  38.0      1      0       2
2       3  26.0      0      0       1
3       1  35.0      1      0       2
4       3  35.0      0      0       1

In [45]:
def classify_family_type(num):
    if(num == 1):
        return 0 #alone
    elif(num > 1 and num <= 4):
        return 1 #small family
    else:
        return 2 #large family

In [46]:
X['Family_type'] = X['Family'].apply(classify_family_type)

In [47]:
X.head()

   Pclass   Age  SibSp  Parch  Family  Family_type
0       3  22.0      1      0       2            1
1       1  38.0      1      0       2            1
2       3  26.0      0      0       1            0
3       1  35.0      1      0       2            1
4       3  35.0      0      0       1            0

In [48]:
X = X.drop(columns=['SibSp', 'Parch', 'Family'])
X.head()

   Pclass   Age  Family_type
0       3  22.0            1
1       1  38.0            1
2       3  26.0            0
3       1  35.0            1
4       3  35.0            0

In [49]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv = 20))

np.float64(0.7003174603174602)

In [50]:
# Accuracy increased here with feature construction

## Feature splitting

In [51]:
df_2 = pd.read_csv("../data/Titanic_dataset.csv")
df_2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [52]:
df_2['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [53]:
df_2['Name'].str.split(',', expand = True)[1].str.split('.', expand = True)[0]

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: 0, Length: 891, dtype: str

In [54]:
df_2['Title'] = df_2['Name'].str.split(',', expand = True)[1].str.split('.', expand = True)[0]
df_2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [55]:
df_2['Title'].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [56]:
(df_2.groupby('Title')['Survived'].mean()).sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [57]:
# Both married and unmarried women had a high survival rate

In [58]:
df_2['Is_married'] = 0

In [59]:
df_2.loc[df_2['Title'] == 'Mrs', 'Is_married'] = 1

In [60]:
df_2['Is_married']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_married, Length: 891, dtype: int64

In [61]:
df_2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Is_married
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,0

In [62]:
# done

In [63]:
# :)