In [116]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import Binarizer

In [117]:
df = pd.read_csv('../data/Titanic_dataset.csv', usecols=['Survived', 'Age', 'SibSp', 'Fare', 'Parch'])
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [118]:
df.isnull().sum()

Survived      0
Age         177
SibSp         0
Parch         0
Fare          0
dtype: int64

In [119]:
df.dropna(inplace=True)

In [120]:
df.isnull().sum()

Survived    0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [121]:
df['family'] = df['SibSp'] + df['Parch']
df

     Survived   Age  SibSp  Parch     Fare  family
0           0  22.0      1      0   7.2500       1
1           1  38.0      1      0  71.2833       1
2           1  26.0      0      0   7.9250       0
3           1  35.0      1      0  53.1000       1
4           0  35.0      0      0   8.0500       0
..        ...   ...    ...    ...      ...     ...
885         0  39.0      0      5  29.1250       5
886         0  27.0      0      0  13.0000       0
887         1  19.0      0      0  30.0000       0
889         1  26.0      0      0  30.0000       0
890         0  32.0      0      0   7.7500       0

[714 rows x 6 columns]

In [122]:
df = df.drop(columns=['SibSp', 'Parch'])
df

     Survived   Age     Fare  family
0           0  22.0   7.2500       1
1           1  38.0  71.2833       1
2           1  26.0   7.9250       0
3           1  35.0  53.1000       1
4           0  35.0   8.0500       0
..        ...   ...      ...     ...
885         0  39.0  29.1250       5
886         0  27.0  13.0000       0
887         1  19.0  30.0000       0
889         1  26.0  30.0000       0
890         0  32.0   7.7500       0

[714 rows x 4 columns]

In [123]:
X = df.drop(columns='Survived')
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

      Age      Fare  family
328  31.0   20.5250       2
73   26.0   14.4542       1
253  30.0   16.1000       1
719  33.0    7.7750       0
666  25.0   13.0000       0
..    ...       ...     ...
92   46.0   61.1750       1
134  25.0   13.0000       0
337  41.0  134.5000       0
548  33.0   20.5250       2
130  33.0    7.8958       0

[571 rows x 3 columns]

In [124]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.6293706293706294

In [125]:
np.mean(cross_val_score(DecisionTreeClassifier(), X, y, scoring='accuracy', cv = 10))

np.float64(0.6513302034428794)

In [126]:
tf = ColumnTransformer([
    ('tf1', Binarizer(copy = False), [2])
], remainder='passthrough')

In [127]:
X_train_tf = tf.fit_transform(X_train)
X_test_tf = tf.transform(X_test)
X_train_tf

array([[  1.    ,  31.    ,  20.525 ],
       [  1.    ,  26.    ,  14.4542],
       [  1.    ,  30.    ,  16.1   ],
       ...,
       [  0.    ,  41.    , 134.5   ],
       [  1.    ,  33.    ,  20.525 ],
       [  0.    ,  33.    ,   7.8958]], shape=(571, 3))

In [128]:
X_train_tf

array([[  1.    ,  31.    ,  20.525 ],
       [  1.    ,  26.    ,  14.4542],
       [  1.    ,  30.    ,  16.1   ],
       ...,
       [  0.    ,  41.    , 134.5   ],
       [  1.    ,  33.    ,  20.525 ],
       [  0.    ,  33.    ,   7.8958]], shape=(571, 3))

In [129]:
model = DecisionTreeClassifier()
model.fit(X_train_tf, y_train)
y_pred = model.predict(X_test_tf)

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.6223776223776224

In [130]:
X_tf = tf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(), X_tf, y, scoring='accuracy', cv = 10))

np.float64(0.6318466353677621)