In [68]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [69]:
df = pd.read_csv("../../../data/Titanic_dataset.csv", usecols=['Age', 'Pclass', 'Fare', 'Survived'])
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [70]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [71]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
Fare          0
dtype: int64

In [72]:
X = df.drop(columns=['Survived'])
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [73]:
knn = KNNImputer(n_neighbors=10)
X_train_knn = knn.fit_transform(X_train)
X_test_knn = knn.transform(X_test)

X_train_trf1 = pd.DataFrame(X_train_knn, columns=X_train.columns)
X_test_trf1 = pd.DataFrame(X_test_knn, columns=X_test.columns)

X_train_trf1.head()

   Pclass   Age     Fare
0     1.0  45.5  28.5000
1     2.0  23.0  13.0000
2     3.0  32.0   7.9250
3     3.0  26.0   7.8542
4     3.0   6.0  31.2750

In [74]:
X_train_trf1.isnull().sum()

Pclass    0
Age       0
Fare      0
dtype: int64

In [75]:
lr1 = LogisticRegression()

lr1.fit(X_train_trf1, y_train)

predictions1 = lr1.predict(X_test_trf1)

print(accuracy_score(y_test, predictions1))

0.7486033519553073

In [76]:
# Now comparing with simple imputer

si = SimpleImputer()

X_train_si = si.fit_transform(X_train)
X_test_si = si.transform(X_test)

X_train_trf2 = pd.DataFrame(X_train_si, columns=X_train.columns)
X_test_trf2 = pd.DataFrame(X_test_si, columns=X_test.columns)

X_train_trf2.head()

   Pclass   Age     Fare
0     1.0  45.5  28.5000
1     2.0  23.0  13.0000
2     3.0  32.0   7.9250
3     3.0  26.0   7.8542
4     3.0   6.0  31.2750

In [77]:
X_train_trf2.isnull().sum()

Pclass    0
Age       0
Fare      0
dtype: int64

In [78]:
lr2 = LogisticRegression()

lr2.fit(X_train_trf2, y_train)

predictions2 = lr2.predict(X_test_trf2)

print(accuracy_score(y_test, predictions2))

0.7374301675977654

In [79]:
# KNN Imputer performs better than simple imputer here!!

In [80]:
# :)