In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df_date = pd.read_csv("../data/orders.csv")
df_time = pd.read_csv("../data/messages.csv")

In [4]:
df_date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
df_time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [7]:
df_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [8]:
df_time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [9]:
# By default -- date and time features are treated as str/object dtype

In [11]:
## Converting dtype from str to datetime of orders data ---

df_date['date'] = pd.to_datetime(df_date['date'])

In [12]:
df_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

**Extract year**

In [13]:
df_date['year'] = df_date['date'].dt.year

In [14]:
df_date.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

**Extract Month Number and Month Name**

In [15]:
df_date['month_number'] = df_date['date'].dt.month

In [16]:
df_date.head()

        date  product_id  city_id  orders  year  month_number
0 2019-12-10        5628       25       3  2019            12
1 2018-08-15        3646       14     157  2018             8
2 2018-10-23        1859       25       1  2018            10
3 2019-08-17        7292       25       1  2019             8
4 2019-01-06        4344       25       3  2019             1

In [22]:
df_date['month_name'] = df_date['date'].dt.month_name()

In [23]:
df_date

          date  product_id  city_id  orders  year  month_number month_name
0   2019-12-10        5628       25       3  2019            12   December
1   2018-08-15        3646       14     157  2018             8     August
2   2018-10-23        1859       25       1  2018            10    October
3   2019-08-17        7292       25       1  2019             8     August
4   2019-01-06        4344       25       3  2019             1    January
..         ...         ...      ...     ...   ...           ...        ...
995 2018-10-08         255       13       1  2018            10    October
996 2018-12-06        5521        7       1  2018            12   December
997 2019-05-07         487       26      14  2019             5        May
998 2019-03-03        1503       21       2  2019             3      March
999 2019-10-15        6371        7      22  2019            10    October

[1000 rows x 7 columns]

**Extract Day no (of month), Day no(of week), Day name**

In [24]:
df_date['day_number'] = df_date['date'].dt.day

In [26]:
df_date.head()

,date,product_id,city_id,orders,year,month_number,month_name,day_number
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [27]:
df_date['day_number_of_week'] = df_date['date'].dt.dayofweek

In [29]:
df_date.head()

,date,product_id,city_id,orders,year,month_number,month_name,day_number,day_number_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [30]:
df_date['day_name'] = df_date['date'].dt.day_name()

In [31]:
df_date.head()

,date,product_id,city_id,orders,year,month_number,month_name,day_number,day_number_of_week,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

**Is it a weekend or not?**

In [32]:
df_date['is_weekend'] = np.where(df_date['day_name'].isin(['Saturday', 'Sunday']), 1, 0)

In [34]:
df_date.head()

,date,product_id,city_id,orders,year,month_number,month_name,day_number,day_number_of_week,day_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

**Which week of the year?**

In [36]:
df_date['week_no'] = df_date['date'].dt.isocalendar().week

In [37]:
df_date.head()

,date,product_id,city_id,orders,year,month_number,month_name,day_number,day_number_of_week,day_name,is_weekend,week_no
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

**Extract quarter**

In [38]:
df_date['quarter_no'] = df_date['date'].dt.quarter

In [40]:
df_date.head()

,date,product_id,city_id,orders,year,month_number,month_name,day_number,day_number_of_week,day_name,is_weekend,week_no,quarter_no
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

**Extract semester**

In [42]:
df_date['semester'] = np.where(df_date['quarter_no'].isin([1,2]), 2, 1)

In [43]:
df_date.head()

,date,product_id,city_id,orders,year,month_number,month_name,day_number,day_number_of_week,day_name,is_weekend,week_no,quarter_no,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,1
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,1
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,1
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,2

**Extract time elapsed between dates**

In [45]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 9, 23, 18, 18, 21, 693973)

In [46]:
today - df_date['date']

0     2479 days 18:18:21.693973
1     2961 days 18:18:21.693973
2     2892 days 18:18:21.693973
3     2594 days 18:18:21.693973
4     2817 days 18:18:21.693973
                 ...
995   2907 days 18:18:21.693973
996   2848 days 18:18:21.693973
997   2696 days 18:18:21.693973
998   2761 days 18:18:21.693973
999   2535 days 18:18:21.693973
Name: date, Length: 1000, dtype: timedelta64[us]

In [47]:
# No of days elapsed --

(today - df_date['date']).dt.days

0      2479
1      2961
2      2892
3      2594
4      2817
       ...
995    2907
996    2848
997    2696
998    2761
999    2535
Name: date, Length: 1000, dtype: int64

In [51]:
# No of months passed --

np.round((today - df_date['date']) / np.timedelta64(30, 'D'), 0)

0      83.0
1      99.0
2      96.0
3      86.0
4      94.0
       ...
995    97.0
996    95.0
997    90.0
998    92.0
999    85.0
Name: date, Length: 1000, dtype: float64

In [52]:
## Now working with messages data --

In [53]:
df_time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [54]:
df_time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [55]:
# Converting the dtype from string to datetime

df_time['date'] = pd.to_datetime(df_time['date'])

In [56]:
df_time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [57]:
df_time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

**Extracting hours, minutes and seconds**

In [59]:
df_time['hour'] = df_time['date'].dt.hour
df_time['minutes'] = df_time['date'].dt.minute
df_time['seconds'] = df_time['date'].dt.second

In [61]:
df_time.head()

,date,msg,hour,minutes,seconds
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

**Extracting only the time portion**

In [62]:
df_time['time'] = df_time['date'].dt.time

In [63]:
df_time.head()

,date,msg,hour,minutes,seconds,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

**Extracting time elapsed**

In [64]:
today - df_time['date']

0     4665 days 17:28:21.693973
1     4529 days 18:38:21.693973
2     5015 days 17:57:21.693973
3     4317 days 17:47:21.693973
4     4714 days 19:07:21.693973
                 ...
995   5304 days 17:28:21.693973
996   4625 days 19:04:21.693973
997   5090 days 18:41:21.693973
998   5206 days 18:44:21.693973
999   4478 days 18:53:21.693973
Name: date, Length: 1000, dtype: timedelta64[us]

In [65]:
# seconds

np.round((today - df_time['date']) / np.timedelta64(1, 's'), 0)

0      403118902.0
1      391372702.0
2      433360642.0
3      373052842.0
4      407358442.0
          ...
995    458328502.0
996    399668662.0
997    439843282.0
998    449865862.0
999    386967202.0
Name: date, Length: 1000, dtype: float64

In [70]:
# minutes

np.round((today - df_time['date']) / np.timedelta64(1, 'm'), 0)

0      6718648.0
1      6522878.0
2      7222677.0
3      6217547.0
4      6789307.0
         ...
995    7638808.0
996    6661144.0
997    7330721.0
998    7497764.0
999    6449453.0
Name: date, Length: 1000, dtype: float64

In [71]:
# hours

np.round((today - df_time['date']) / np.timedelta64(1, 'h'), 0)

0      111977.0
1      108715.0
2      120378.0
3      103626.0
4      113155.0
         ...
995    127313.0
996    111019.0
997    122179.0
998    124963.0
999    107491.0
Name: date, Length: 1000, dtype: float64

In [68]:
# done :)